apiVersion: v1
kind: Deployment
metadata:
  name: recommand-api
  labels:
    app: recommand-api

spec:
  selector:
    matchLabels:
      app: recommand-api

  template:
    metadata:
      labels:
        app: recommand-api

    spec:
      containers:
        - name: recommand-api
          image: loverduck97/kkoma-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-secret