apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommand-api
  labels:
    app: recommand

spec:
  selector:
    matchLabels:
      app: recommand-api

  template:
    metadata:
      labels:
        app: recommand-api

    spec:
      containers:
        - name: recommand-api
          image: loverduck97/kkoma-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: recommand-svc
spec:
  ports:
    - name: service
      nodePort: 5000
      port: 5000
      targetPort: 5000
  selector:
    app: recommand