spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

kakao:
  client:
    id:
    secret:

token:
  secret:
  access-token-expiration-time:
  refresh-token-expiration-time:

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    s3:
      bucket: kkoma

