server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.type: debug
    com.konoha: debug

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
